language: go

go:
  - "1.12.x"
  - "1.13.x"

env:
  - GO111MODULE=on

install:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.20.1

script:
  - make test
  - golangci-lint run

after_success:
  - go get github.com/mattn/goveralls
  - goveralls -coverprofile=coverage.out -service=travis-ci
